### ISSUE TITLE
connection from inside mullvad vpn loops with no error message

### ISSUE THREAD

**Issue by vv01f** [Slethen/mullvad#2]
when inside a mullvad vpn the target country is looped over possible hosts without establishing any connection and without an error

* possibly there should be a check if the current exit is one of the vpn's own

**Comment by joelbduncan** [comment]
This repository is not the main Mullvad repo, this is purely for building Mullvad for an unofficial copr repo with a few patches to get Mullvad working on Fedora. Please contact Mullvad directly for feature requests, thanks!
