### ISSUE TITLE
Optional b/w toolbar icon for OSX

### ISSUE THREAD

**Issue by brantz** [Slethen/mullvad#3]
It would be nice to have an optional b/w version of the toolbar icon for osx for those who don't like their toolbar being lit up like a christmas tree ;)

**Comment by joelbduncan** [comment]
This repository is not the main Mullvad repo, this is purely for building Mullvad for an unofficial copr repo with a few patches to get Mullvad working on Fedora. Please contact Mullvad directly for feature requests, thanks!
